### ISSUE TITLE
Why did you drop old tags/releases?

### ISSUE THREAD

**Issue by pashamesh** [nblackburn/laravel-hashids#15]
Hi,
Why did you drop old tags/releases? Currently I only can see `1.2.4` tag.

**Comment by nblackburn** [comment]
My apologies, i have been working hard to bring the code up to a standard i am happy with.

During the process i decided it was best to drop the older tags to prevent those versions from being used to avoid confusion as the code wasn't final.

Now the code is production ready, this wont happen again and all future releases will be archived.
